default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 32768
  username: postgres
  password: postgrespw
  timeout: 5000

development:
  <<: *default
  database: postgres
test:
  <<: *default
  database: postgres

production:
  <<: *default
  database: postgres
